#ifndef _INCLUDED_SENSOR_SONYIMX214_PLLDEFINES_H_
#define _INCLUDED_SENSOR_SONYIMX214_PLLDEFINES_H_

#define SENSOR_SONY_IMX214_PLL_INC_FREQUENZ         27
//u8.u8
#define SENSOR_SONY_IMX214_PLL_EXCK_FREQ_U8_U8      (SENSOR_SONY_IMX214_PLL_INC_FREQUENZ * 256)
#define SENSOR_SONY_IMX214_PLL_VT_PREDIV         1
#define SENSOR_SONY_IMX214_PLL_VT_MPY            16
#define SENSOR_SONY_IMX214_PLL_OP_PREDIV         1
#define SENSOR_SONY_IMX214_PLL_OP_MPY            16
#define SENSOR_SONY_IMX214_PLL_MULT_DRIV            0
#define SENSOR_SONY_IMX214_PLL_VT_SYS_CLK_DIV       4
#define SENSOR_SONY_IMX214_PLL_VT_PIX_CLK_DIV       5
#define SENSOR_SONY_IMX214_PLL_OP_SYS_CLK_DIV       1
#define SENSOR_SONY_IMX214_PLL_OP_PIX_CLK_DIV       10

#define SENSOR_SONY_IMX214_CSI_LANE_MODE            1
#define SENSOR_SONY_IMX214_CSI_DT_FMT_L            10

//begin: Mipi global timing setting datasheet imx215 application note page 34
//NOTE: this is a example of the calculation which you can find in data sheet
//      please calculate the formula manually due to you get decimal rounding errors!!!
#define SENSOR_SONY_IMX214_OPPXCK_DENOMINATOR_U16   (SENSOR_SONY_IMX214_PLL_VT_PREDIV*SENSOR_SONY_IMX214_PLL_VT_SYS_CLK_DIV* \
                                                     SENSOR_SONY_IMX214_PLL_VT_PIX_CLK_DIV)
#define SENSOR_SONY_IMX214_OPPXCK_NUMERATOR_U16_U16 (SENSOR_SONY_IMX214_PLL_EXCK_FREQ_U8_U8*SENSOR_SONY_IMX214_PLL_VT_MPY * 256.0)
#define SENSOR_SONY_IMX214_OPPXCK_U16_U16           (SENSOR_SONY_IMX214_OPPXCK_NUMERATOR_U16_U16/SENSOR_SONY_IMX214_OPPXCK_DENOMINATOR_U16)
//#define SENSOR_SONY_IMX214_OPPXCK_U16_U16           (86.4*256*256)
#define SENSOR_SONY_IMX214_OUTPUT_BITRATE_U16_U16   (SENSOR_SONY_IMX214_OPPXCK_U16_U16 * SENSOR_SONY_IMX214_CSI_DT_FMT_L)


#define SENSOR_SONY_IMX214_REQ_LINK_RATE_MBPS_U16_U16       ((SENSOR_SONY_IMX214_CSI_LANE_MODE + 1)*SENSOR_SONY_IMX214_OUTPUT_BITRATE_U16_U16)
//end Mipi global timing setting
#endif
