var searchData=
[
  ['vcoroutineschedule_16831',['vCoRoutineSchedule',['../group__v_co_routine_schedule.html',1,'']]],
  ['vqueuedelete_16832',['vQueueDelete',['../group__v_queue_delete.html',1,'']]],
  ['vsemaphorecreatebinary_16833',['vSemaphoreCreateBinary',['../group__v_semaphore_create_binary.html',1,'']]],
  ['vsemaphoredelete_16834',['vSemaphoreDelete',['../group__v_semaphore_delete.html',1,'']]],
  ['vstreambufferdelete_16835',['vStreamBufferDelete',['../group__v_stream_buffer_delete.html',1,'']]],
  ['vtaskdelay_16836',['vTaskDelay',['../group__v_task_delay.html',1,'']]],
  ['vtaskdelayuntil_16837',['vTaskDelayUntil',['../group__v_task_delay_until.html',1,'']]],
  ['vtaskdelete_16838',['vTaskDelete',['../group__v_task_delete.html',1,'']]],
  ['vtaskendscheduler_16839',['vTaskEndScheduler',['../group__v_task_end_scheduler.html',1,'']]],
  ['vtaskgetinfo_16840',['vTaskGetInfo',['../group__v_task_get_info.html',1,'']]],
  ['vtaskgetruntimestats_16841',['vTaskGetRunTimeStats',['../group__v_task_get_run_time_stats.html',1,'']]],
  ['vtasklist_16842',['vTaskList',['../group__v_task_list.html',1,'']]],
  ['vtaskpriorityset_16843',['vTaskPrioritySet',['../group__v_task_priority_set.html',1,'']]],
  ['vtaskresume_16844',['vTaskResume',['../group__v_task_resume.html',1,'']]],
  ['vtaskresumefromisr_16845',['vTaskResumeFromISR',['../group__v_task_resume_from_i_s_r.html',1,'']]],
  ['vtaskstartscheduler_16846',['vTaskStartScheduler',['../group__v_task_start_scheduler.html',1,'']]],
  ['vtasksuspend_16847',['vTaskSuspend',['../group__v_task_suspend.html',1,'']]],
  ['vtasksuspendall_16848',['vTaskSuspendAll',['../group__v_task_suspend_all.html',1,'']]]
];
