-- ***************************************************************************************
-- File components.vhd auto-generated by packaging utiltiy on Fri Oct 12 18:03:36 2007 GMT
-- ***************************************************************************************

library ieee;
use ieee.std_logic_1164.all;

package components is
component CORE16550 
   GENERIC (
      -- DEVICE FAMILY 
      FAMILY                         :  integer := 15); 
   PORT (
      -- APB interface
      
      -- APB system reset
      PCLK             : IN STD_LOGIC;		-- APB system clock
      PRESETN          : IN STD_LOGIC;
      PADDR            : IN STD_LOGIC_VECTOR(4 DOWNTO 0);		-- Latched address
      PSEL             : IN STD_LOGIC;
      PENABLE          : IN STD_LOGIC;
      PWRITE           : IN STD_LOGIC;
      PWDATA           : IN STD_LOGIC_VECTOR(7 DOWNTO 0);		-- 8 bit write data
      PRDATA           : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);		-- 8 bit read data 
      CTSN             : IN STD_LOGIC;
      DCDN             : IN STD_LOGIC;
      DSRN             : IN STD_LOGIC;
      RIN              : IN STD_LOGIC;
      SIN              : IN STD_LOGIC;
      SOUT             : OUT STD_LOGIC;
      BAUDOUTN         : OUT STD_LOGIC;
      DTRN             : OUT STD_LOGIC;
      RTSN             : OUT STD_LOGIC;
      OUT1N            : OUT STD_LOGIC;
      OUT2N            : OUT STD_LOGIC;
      INTR             : OUT STD_LOGIC;
      RXRDYN           : OUT STD_LOGIC;
      TXRDYN           : OUT STD_LOGIC;
      RXFIFO_FULL      : OUT STD_LOGIC;
      RXFIFO_EMPTY     : OUT STD_LOGIC
   );
end component;

end components;